exclude:

# Folders
# BurgerApp
- /Front-end/BurgerApp/e2e/.*
- /Front-end/BurgerApp/src/assets/.*
- /Front-end/BurgerApp/src/environments/.*
# InformatieManagerApp
- /Front-end/InformatieManagerApp/e2e/.*
- /Front-end/InformatieManagerApp/src/assets/.*
- /Front-end/InformatieManagerApp/src/environments/.*


# Files
# BurgerApp
- /Front-end/BurgerApp/.editorconfig
- /Front-end/BurgerApp/.gitignore
- /Front-end/BurgerApp/angular.json
- /Front-end/BurgerApp/package-lock.json
- /Front-end/BurgerApp/package.json
- /Front-end/BurgerApp/README.md
- /Front-end/BurgerApp/tsconfig.json
- /Front-end/BurgerApp/tslint.json
- /Front-end/BurgerApp/yarn.lock
- /Front-end/BurgerApp/src/browserslist
- /Front-end/BurgerApp/src/favicon.ico
- /Front-end/BurgerApp/src/karma.conf.js
- /Front-end/BurgerApp/src/main.ts
- /Front-end/BurgerApp/src/polyfills.ts
- /Front-end/BurgerApp/src/test.ts
- /Front-end/BurgerApp/src/tsconfig.app.json
- /Front-end/BurgerApp/src/tsconfig.spec.json
- /Front-end/BurgerApp/src/tslint.json
# InformatieManagerApp
- /Front-end/InformatieManagerApp/.editorconfig
- /Front-end/InformatieManagerApp/.gitignore
- /Front-end/InformatieManagerApp/angular.json
- /Front-end/InformatieManagerApp/package-lock.json
- /Front-end/InformatieManagerApp/package.json
- /Front-end/InformatieManagerApp/README.md
- /Front-end/InformatieManagerApp/tsconfig.json
- /Front-end/InformatieManagerApp/tslint.json
- /Front-end/InformatieManagerApp/yarn.lock
- /Front-end/InformatieManagerApp/src/browserslist
- /Front-end/InformatieManagerApp/src/favicon.ico
- /Front-end/InformatieManagerApp/src/karma.conf.js
- /Front-end/InformatieManagerApp/src/main.ts
- /Front-end/InformatieManagerApp/src/polyfills.ts
- /Front-end/InformatieManagerApp/src/test.ts
- /Front-end/InformatieManagerApp/src/tsconfig.app.json
- /Front-end/InformatieManagerApp/src/tsconfig.spec.json
- /Front-end/InformatieManagerApp/src/tslint.json


# Examples
# - .*/FileYouWantToExclude\.java
# - /DirectoryYouWantToExclude/.*